application:
  security:
    jwt:
      secret-key: 2902C1765462406CD450F8C09DF20DE20CDABFE8BF01D15CC769F81E6099DD6F089812F96B9BABE79A4F1B5053444D2B321E781C6D973AA99F92CDEE4CA2AADF
      access-expiration: 8640000
      refresh-expiration: 604800000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3316/book_companion_app
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 500
        timeout: 3000
        writetimeout: 5000


