services:
  mysql:
    container_name: mysql-bca
    image: mysql:8.0.37
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: book_companion_app
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3316:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - spring-app
  mail-dev:
    container_name: mail-dev-bca
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  bca-api:
    container_name: bca-api
    image: bca/bca:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-app
    depends_on:
      - mysql
  bca-ui:
    container_name: bca-ui
    image: bca/bca-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-app
    depends_on:
      - bca-api

volumes:
  mysql:
    driver: local

networks:
  spring-app:
    driver: bridge